- name: Add key for passenger
  apt_key: >
    url=http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0xAC40B2F7 
    state=present

- name: Apt via https
  apt: >
    name=apt-transport-https 
    state=present

- name: Apt add passenger to list  
  apt_repository: >
    repo='deb https://oss-binaries.phusionpassenger.com/apt/passenger {{ansible_distribution_release}} main' 
    state=present 
    update_cache=yes  

- name: Install nginx
  action: apt pkg={{ item }} state=installed
  with_items:
    - nginx-extras
    - passenger

- name: Ensure log directory exist
  file: >
    path={{ nginx_log_dir }} 
    state=directory 
    owner={{nginx_user}} 
    group={{nginx_group}} 
    mode=0755

- name: Get passenger_root path
  shell: /usr/bin/passenger-config --root
  register: passenger_root_path

#- debug: >
#    msg="passenger_root_path : {{ passenger_root_path.stdout }}"
#  tags:
#    - debug
  

- name: Get ruby path
  shell: which ruby
  register: passenger_ruby_path

#- debug: >
#    msg="passenger_ruby_path : {{ passenger_ruby_path.stdout }}"

- name: Copy the nginx configuration file
  template: >
    src=nginx.conf.j2 
    dest=/etc/nginx/nginx.conf
  notify:
   - restart nginx


- name: Disable the default site
  file: >
    path=/etc/nginx/sites-enabled/default 
    state=absent
  notify:
    - reload nginx

- name: Start the nginx service
  service: name=nginx state=started enabled=yes

