defaults: &defaults
  adapter: mysql2
  username: root
  password: 
  encoding: utf8
  host: localhost

development:
  <<: *defaults
  database: barbier_dev

test:
  <<: *defaults
  database: barbier_test

staging:
  <<: *defaults
  database: barbier_staging

production:
  <<: *defaults
  database: barbier_production
  socket: /var/run/mysqld/mysqld.sock
