defaults: &defaults
  adapter: mysql2
  username: root
  password: 
  encoding: utf8
  host: localhost

development:
  <<: *defaults
  database: jobsite_dev

test:
  <<: *defaults
  database: jobsite_test

staging:
  <<: *defaults
  database: jobsite_staging
  socket: /var/run/mysqld/mysqld.sock

production:
  <<: *defaults
  database: jobsite_production
  socket: /var/run/mysqld/mysqld.sock