- name: Install a full stack Rails server
  hosts: servers
  gather_facts: true
  user: root

  vars_files:
    - vars/{{ rails_env }}_passwords.yml

#  tasks:
#    - debug: msg="{{ deploy_user_password }}"
#      tags:
#        - debug

  roles:
    - common
    - ruby
    - nginx_passenger
    - mysql
    - { role: app, tags: [ 'app' ] }
    - monit
    - firewall



