# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provision 'file',
    source: '~/.ssh/id_rsa.pub',
    destination: '/home/vagrant/root_pubkey'

  config.vm.provision 'shell', path: 'authorized_keys.sh'

  config.vm.network :private_network, ip: '192.168.33.10'
  config.vm.hostname = 'myapp.dev'
end
